insert into table ddl.tb_xdr_ifc_mw 
select
 Length ,
 City ,
 interface ,
 xdrId ,
 rat ,
 imsi ,
 imei ,
 msisdn ,
 ProcedureType ,
 ProcedureStartTime ,
 ProcedureEndTime ,
 ServiceType ,
 ProcedureStatus ,
 CALLINGNUMBER ,
 CALLEDNUMBER ,
 CALLINGPARTYURI ,
 REQUESTURI ,
 USERIP ,
 CALLID ,
 ICID ,
 SOURCENEIP ,
 SOURCENEPORT ,
 DESTNEIP ,
 DESTNEPORT ,
 CALLSIDE ,
 SOURCEACCESSTYPE ,
 SOURCEECI ,
 SOURCETAC ,
 SOURCEIMSI ,
 SOURCEIMEI ,
 DESTACCESSTYPE ,
 DESTECI ,
 DESTTAC ,
 DESTIMSI ,
 DESTIMEI ,
 AUTHTYPE ,
 EXPIRESTIMEREQ ,
 EXPIRESTIMERSP ,
 CALLINGSDPIPADDR ,
 CALLINGAUDIOSDPPORT ,
 CALLINGVIDEOSDPPORT ,
 CALLEDSDPIPADDR ,
 CALLEDAUDIOSDPPORT ,
 CALLEDVIDEOPORT ,
 AUDIOCODEC ,
 VIDEOCODEC ,
 REDIRECTINGPARTYADDRESS ,
 ORIGINALPARTYADDRESS ,
 REDIRECTREASON ,
 RESPONSECODE ,
 FINISHWARNINGCODE ,
 FINISHREASONPROTOCOL ,
 FINISHREASONCAUSE ,
 FIRFAILTIME ,
 FIRSTFAILNEIP ,
 ALERTINGTIME ,
 ANSWERTIME ,
 RELEASETIME ,
 CALLDURATION ,
 AUTHREQTIME ,
 AUTHRSPTIME ,
 STNSR ,
 ATCFMGMT ,
 ATUSTI ,
 CMSISDN ,
 SSI,
 rangetime,
 (case 
   when ProcedureType = 1 and INTERFACE=14 and ProcedureStatus in (1,3) then 1
   when ProcedureType = 5 and INTERFACE=14 and CALLSIDE = 0 and ALERTINGTIME = 'FFFF' and ServiceType = 0 then 4
   when ProcedureType = 5 and INTERFACE=14 and CALLSIDE = 0 and ALERTINGTIME = 'FFFF' and ServiceType = 1 then 6
 end)
 from default.tb_xdr_ifc_mw ;
 
 insert into table default.tb_xdr_ifc_mw_exception
 select * from ddl.tb_xdr_ifc_mw where etype=1;
 
 
 
 
 insert INTO table ddl.tb_xdr_ifc_gx 
 select 
 Length ,
 City ,
 Interface ,
 xdrId ,
 rat ,
 imsi ,
 imei ,
 msisdn ,
 ProcedureType ,
 ProcedureStartTime ,
 ProcedureEndTime ,
 ICID ,
 ORIGINREALM ,
 DESTINATIONREALM ,
 ORIGINHOST ,
 DESTINATIONHOST ,
 SGSNSGWSIGIP ,
 AFAPPID ,
 CCREQUESTTYPE ,
 RXREQUESTTYPE ,
 MEDIATYPE ,
 ABORTCAUSE ,
 RESULTCODE ,
 EXPERIMENTALRESULTCODE ,
 SESSIONRELEASECAUSE,
 (case
   when ProcedureType = 3 AND interface = 26 and ABORTCAUSE in (0,1,2,4) and MEDIATYPE = 0 then 5 
   when ProcedureType = 3 AND interface = 26 and ABORTCAUSE in (0,1,2,4) and MEDIATYPE = 1 then 7 else 0 
 end)
 from default.tb_xdr_ifc_gx
 
insert table ddl.tb_xdr_ifc_x2
select
 Length ,
 City ,
 Interface ,
 xdrId ,
 rat ,
 imsi ,
 imei ,
 msisdn ,
 ProcedureType ,
 ProcedureStartTime ,
 ProcedureEndTime ,
 ProcedureStatus ,
 SourceCellID ,
 TargetCellID ,
 SourceeNBID ,
 TargeteNBID ,
 MMEUES1APID ,
 MMEGroupID ,
 MMECode ,
 RequestCause ,
 FailureCause ,
 EPSBearerNumber ,
 Bearer1ID ,
 Bearer1Status ,
 Bearer2ID ,
 Bearer2Status ,
 Bearer3ID ,
 Bearer3Status ,
 Bearer4ID ,
 Bearer4Status ,
 Bearer5ID ,
 Bearer5Status ,
 Bearer6ID ,
 Bearer6Status ,
 Bearer7ID ,
 Bearer7Status ,
 Bearer8ID ,
 Bearer8Status ,
 Bearer9ID ,
 Bearer9Status ,
 Bearer10ID ,
 Bearer10Status ,
 Bearer11ID ,
 Bearer11Status ,
 Bearer12ID ,
 Bearer12Status ,
 Bearer13ID ,
 Bearer13Status ,
 Bearer14ID ,
 Bearer14Status ,
 Bearer15ID ,
 Bearer15Status ,
 Bearer16ID ,
 Bearer16Status ,
 rangetime,
 (case
   when procedureType = 1 and ProcedureStatus in(1,255) and (failurecause <> 1000 or failurecause is null) then 10 else 0
 end ) as etype
 from default.tb_xdr_ifc_x2

----------------------------------------------------
INSERT into TABLE  ddl.tb_xdr_ifc_uu 
 select
  Length ,
  City ,
  Interface ,
  xdrId ,
  rat ,
  imsi ,
  imei ,
  msisdn ,
  ProcedureType ,
  ProcedureStartTime ,
  ProcedureEndTime ,
  keyword1 ,
  keyword2 ,
  ProcedureStatus ,
  plmnid ,
  enbid ,
  cellid ,
  crnti ,
  TargeteNBID ,
  TargetCellID ,
  TargetCRNTI ,
  MMEUES1APID ,
  MMEGroupID ,
  MMECode ,
  MTMSI ,
  CSFBIndication ,
  RedirectedNetwork ,
  EPSBearerNumber ,
  Bearer1ID ,
  Bearer1Status ,
  Bearer2ID ,
  Bearer2Status ,
  Bearer3ID ,
  Bearer3Status ,
  Bearer4ID ,
  Bearer4Status ,
  Bearer5ID ,
  Bearer5Status ,
  Bearer6ID ,
  Bearer6Status ,
  Bearer7ID ,
  Bearer7Status ,
  Bearer8ID ,
  Bearer8Status ,
  Bearer9ID ,
  Bearer9Status ,
  Bearer10ID ,
  Bearer10Status ,
  Bearer11ID ,
  Bearer11Status ,
  Bearer12ID ,
  Bearer12Status ,
  Bearer13ID ,
  Bearer13Status ,
  Bearer14ID ,
  Bearer14Status ,
  Bearer15ID ,
  Bearer15Status ,
  Bearer0ID ,
  Bearer0Status ,
  rangetime,
  (case 
    when ProcedureType = 7 and ProcedureStatus  in (1,255) then 10 else 0 end) 
  from default.tb_xdr_ifc_uu
 
 insert into table default.tb_xdr_ifc_uu_exception
select * from ddl.tb_xdr_ifc_uu where etype=10;
