SELECT
	x2.PARENTXDRID,
	x2. LENGTH,
	x2.CITY,
	x2.INTERFACE,
	x2.XDRID,
	x2.RAT,
	S1.IMSI,
	S1.IMEI,
	S1.MSISDN,
	x2.PROCEDURETYPE,
	x2.PROCEDURESTARTTIME,
	x2.PROCEDUREENDTIME,
	x2.PROCEDURESTATUS,
	x2.CELLID,
	x2.TARGETCELLID,
	x2.ENBID,
	x2.TARGETENBID,
	x2.MMEUES1APID,
	x2.MMEGROUPID,
	x2.MMECODE,
	x2.REQUESTCAUSE,
	x2.FAILURECAUSE,
	x2.EPSBEARERNUMBER,
	x2.BEARER0ID,
	x2.BEARER0STATUS,
	x2.BEARER1ID,
	x2.BEARER1STATUS,
	x2.BEARER2ID,
	x2.BEARER2STATUS,
	x2.BEARER3ID,
	x2.BEARER3STATUS,
	x2.BEARER4ID,
	x2.BEARER4STATUS,
	x2.BEARER5ID,
	x2.BEARER5STATUS,
	x2.BEARER6ID,
	x2.BEARER6STATUS,
	x2.BEARER7ID,
	x2.BEARER7STATUS,
	x2.BEARER8ID,
	x2.BEARER8STATUS,
	x2.BEARER9ID,
	x2.BEARER9STATUS,
	x2.BEARER10ID,
	x2.BEARER10STATUS,
	x2.BEARER11ID,
	x2.BEARER11STATUS,
	x2.BEARER12ID,
	x2.BEARER12STATUS,
	x2.BEARER13ID,
	x2.BEARER13STATUS,
	x2.BEARER14ID,
	x2.BEARER14STATUS,
	x2.BEARER15ID,
	x2.BEARER15STATUS,
	x2.RANGETIME
FROM
	tb_Xdr_ifc_x2 x2
LEFT OUTER JOIN (
	SELECT
		B.IMSI,
		B.IMEI,
		B.MSISDN,
		A .MMEUES1APID,
		A .MMEGROUPID,
		A .MMECODE,
		A .PROCEDUREENDTIME
	FROM
		(
			SELECT
				MMEUES1APID,
				MMEGROUPID,
				MMECODE,
				MIN (PROCEDUREENDTIME) PROCEDUREENDTIME
			FROM
				tb_Xdr_ifc_s1mme
			GROUP BY
				MMEUES1APID,
				MMEGROUPID,
				MMECODE
		) A
	INNER JOIN (
		SELECT
			IMSI,
			IMEI,
			MSISDN,
			MMEUES1APID,
			MMEGROUPID,
			MMECODE,
			PROCEDUREENDTIME
		FROM
			tb_Xdr_ifc_s1mme
	) B ON A .PROCEDUREENDTIME = B.PROCEDUREENDTIME
	AND A .MMEUES1APID = B.MMEUES1APID
	AND A .MMEGROUPID = B.MMEGROUPID
	AND A .MMECODE = B.MMECODE
) S1 ON x2.MMEUES1APID = S1.MMEUES1APID
AND x2.MMEGROUPID = S1.MMEGROUPID
AND x2.MMECODE = S1.MMECODE
WHERE
	x2.PROCEDUREENDTIME - S1.PROCEDUREENDTIME <= 600000